export const data = [
    {
        "id": 1,
        "title": "IV. The Rabbit started violently, dropped the.",
        "slug": "iv-the-rabbit-started-violently-dropped-the",
        "summary": null,
        "image": "c7055661f268f8377f079312ab7dc5c3.png",
        "body": "Duchess, it had entirely disappeared; so the King and the executioner ran wildly up and down looking for it, while the rest of the pack, she could not tell whether they were gardeners, or soldiers, or courtiers, or three of her own children. 'How should I know?' said Alice, surprised at her own courage. 'It's no business of MINE.' The Queen turned crimson with fury, and, after glaring at her for a moment like a wild beast, screamed 'Off with her head! Off--' 'Nonsense!' said Alice, very loudly and decidedly, and the Queen was silent. The King laid his hand upon her arm, and timidly said 'Consider, my dear: she is only a child!' The Queen turned angrily away from him, and said to the Knave 'Turn them over!' The Knave did so, very carefully, with one foot. 'Get up!' said the Queen, in a shrill, loud voice, and the three gardeners instantly jumped up, and began bowing to the King, the Queen, the royal children, and everybody else. 'Leave off that!' screamed the Queen. 'You make me giddy.' And then, turning to the rose-tree, she went on, 'What HAVE you been doing here?' 'May it please your Majesty,' said Two, in a very humble tone, going down on one knee as he spoke, 'we were trying--' 'I see!' said the Queen, who had meanwhile been examining the roses. 'Off with their heads!' and the procession moved on, three of the soldiers remaining behind to execute the unfortunate gardeners, who ran to Alice for protection. 'You shan't be beheaded!' said Alice, and she told her sister, as well as she could for sneezing. There was certainly too much of it in the air. Even the Duchess sneezed occasionally; and as for the baby, it was sneezing and howling alternately without a moment's pause. The only things in the kitchen that did not sneeze, were the cook, and a large cat which was sitting on the ground near the door, staring stupidly up into the sky. Alice went timidly up to the door, and knocked. 'There's no sort of use in knocking,' said the Footman, 'and that for two reasons.",
        "status": "1",
        "created_at": "2021-12-26T04:51:49.000000Z",
        "updated_at": "2021-12-26T04:51:49.000000Z",
        "date": "Dec 26, 2021",
        "author": "Super Admin",
        "image_url": "http://127.0.0.1:8000/uploads/posts/c7055661f268f8377f079312ab7dc5c3.png",
        "user": {
            "id": 1,
            "first_name": "super",
            "last_name": "admin",
            "gender": "male",
            "phone": "78478474574",
            "email": "admin@super.com",
            "email_verified_at": "2021-12-26T04:51:39.000000Z",
            "status": "1",
            "image": null,
            "image_url": "http://127.0.0.1:8000/uploads/noavatar.jpg"
        }
    },
    {
        "id": 2,
        "title": "March Hare went 'Sh! sh!' and the Hatter began.",
        "slug": "march-hare-went-sh-sh-and-the-hatter-began",
        "summary": null,
        "image": "b479d593c05bfce56c1839163e50bbb7.png",
        "body": "Alice replied very readily: 'but that's because it stays the same year for such a long time together.' 'Which is just the case with MINE,' said the Hatter. Alice felt dreadfully puzzled. The Hatter's remark seemed to have no sort of meaning in it, and yet it was certainly English. 'I don't quite understand you,' she said, as politely as she could. 'The Dormouse is asleep again,' said the Hatter, and he poured a little hot tea upon its nose. The Dormouse shook its head impatiently, and walked a little quicker. 'What a pity it wouldn't stay!' sighed the Lory, as soon as it was quite out of sight; and an old Crab took the opportunity of saying to her daughter 'Ah, my dear! Let this be a lesson to you never to lose YOUR temper!' 'Hold your tongue, Ma!' said the young Crab, a little snappishly. 'You're enough to try the patience of an oyster!' 'I wish I had our Dinah here, I know I do!' said Alice aloud, addressing nobody in particular. 'She'd soon fetch it back!' 'And who is Dinah, if I might venture to ask the question?' said the Lory. Alice replied eagerly, for she was always ready to talk about her pet: 'Dinah's our cat. And she's such a capital one for catching mice--oh, I beg your pardon!' cried Alice hastily, afraid that she had hurt the poor animal's feelings. 'I quite forgot you didn't like cats.' 'Not like cats!' cried the Mouse, in a shrill, passionate voice. 'Would YOU like cats if you were me?' 'Well, perhaps not,' said Alice in a soothing tone: 'don't be angry about it. And yet I wish I could show you our cat Dinah: I think you'd take a fancy to cats if you could only see her. She is such a dear quiet thing,' Alice went on, half to herself, as she swam lazily about in the pool, 'and she sits purring so nicely by the fire, licking her paws and washing her face--and she is such a nice soft thing to nurse--and she's such a capital one for catching mice you can't think! And oh, I wish you could see her after the birds! Why, she'll eat a little bird as soon as.",
        "status": "1",
        "created_at": "2021-12-26T04:51:49.000000Z",
        "updated_at": "2021-12-26T04:51:49.000000Z",
        "date": "Dec 26, 2021",
        "author": "Cleora Fisher",
        "image_url": "http://127.0.0.1:8000/uploads/posts/b479d593c05bfce56c1839163e50bbb7.png",
        "user": {
            "id": 5,
            "first_name": "Cleora",
            "last_name": "Fisher",
            "gender": null,
            "phone": "9470404632",
            "email": "hrolfson@example.org",
            "email_verified_at": "2021-12-26T04:51:40.000000Z",
            "status": "1",
            "image": null,
            "image_url": "http://127.0.0.1:8000/uploads/noavatar.jpg"
        }
    },
    {
        "id": 3,
        "title": "I'm mad?' said Alice. 'Why not?' said the Mock.",
        "slug": "im-mad-said-alice-why-not-said-the-mock",
        "summary": null,
        "image": "92690e645dbaab807571a652726fc21c.png",
        "body": "Nile On every golden scale! 'How cheerfully he seems to grin, How neatly spread his claws, And welcome little fishes in With gently smiling jaws!' 'I'm sure those are not the right words,' said poor Alice, and her eyes filled with tears again as she went on, 'I must be Mabel after all, and I shall have to go and live in that poky little house, and have next to no toys to play with, and oh! ever so many lessons to learn! No, I've made up my mind about it; if I'm Mabel, I'll stay down here! It'll be no use their putting their heads down and saying \"Come up again, dear!\" I shall only look up and say \"Who am I then? Tell me that first, and then, if I like being that person, I'll come up: if not, I'll stay down here till I'm somebody else\"--but, oh dear!' cried Alice, with a sudden burst of tears, 'I do wish they WOULD put their heads down! I am so VERY tired of being all alone here!' As she said this she looked down at her feet, they seemed to be almost out of sight, they were getting so far off). 'Oh, my poor little feet, I wonder who will put on your shoes and stockings for you now, dears? I'm sure _I_ shan't be able! I shall be a great deal too far off to trouble myself about you: you must manage the best way you can;--but I must be kind to them,' thought Alice, 'or perhaps they won't walk the way I want to go! Let me see: I'll give them a new pair of boots every Christmas.' And she went on planning to herself how she would manage it. 'They must go by the carrier,' she thought; 'and how funny it'll seem, sending presents to one's own feet! And how odd the directions will look! ALICE'S RIGHT FOOT, ESQ. HEARTHRUG, NEAR THE FENDER, (WITH ALICE'S LOVE). Oh dear, what nonsense I'm talking!' Just then her head struck against the roof of the hall: in fact she was now more than nine feet high, and she at once took up the little golden key and hurried off to the garden door. Poor Alice! It was as much as she could do to hold it. As soon as she was small enough to get.",
        "status": "1",
        "created_at": "2021-12-26T04:51:49.000000Z",
        "updated_at": "2021-12-26T04:51:49.000000Z",
        "date": "Dec 26, 2021",
        "author": "Super Admin",
        "image_url": "http://127.0.0.1:8000/uploads/posts/92690e645dbaab807571a652726fc21c.png",
        "user": {
            "id": 1,
            "first_name": "super",
            "last_name": "admin",
            "gender": "male",
            "phone": "78478474574",
            "email": "admin@super.com",
            "email_verified_at": "2021-12-26T04:51:39.000000Z",
            "status": "1",
            "image": null,
            "image_url": "http://127.0.0.1:8000/uploads/noavatar.jpg"
        }
    },
    {
        "id": 4,
        "title": "The King and Queen of Hearts, and I shall have.",
        "slug": "the-king-and-queen-of-hearts-and-i-shall-have",
        "summary": null,
        "image": "4557289711a9eb887a3ad60bc53ce110.png",
        "body": "Alice whispered to the Gryphon. 'They can't have anything to put down yet, before the trial's begun.' 'They're putting down their names,' the Gryphon whispered in reply, 'for fear they should forget them before the end of the bill, \"French, music, AND WASHING--extra.\"' 'You couldn't have wanted it much,' said Alice; 'living at the bottom of a well?' 'Take some more tea,' the March Hare said to itself in a whisper.) 'That would be grand, certainly,' said Alice thoughtfully: 'but then--I shouldn't be hungry for it, you know.' 'Not at first, perhaps,' said the Hatter: 'but you could keep it to half-past one as long as you liked.' 'Is that the way YOU manage?' Alice asked. The Hatter shook his head mournfully. 'Not I!' he replied. 'We quarrelled last March--just before HE went mad, you know--' (pointing with his tea spoon at the March Hare,) '--it was at the great concert given by the Queen of Hearts, and I had to sing \"Twinkle, twinkle, little bat! How I wonder what you're at!\" You know the song, perhaps?' 'I've heard something like it,' said Alice. 'It goes on, you know,' the Hatter continued, 'in this way:-- \"Up above the world you fly, Like a tea-tray in the sky. Twinkle, twinkle--\"' Here the Dormouse shook itself, and began singing in its sleep 'Twinkle, twinkle, twinkle, twinkle--' and went on so long that they had to pinch it to make it stop. 'Well, I'd hardly finished the first verse,' said the Hatter, 'when the Queen jumped up and bawled out, \"He's murdering the time! Off with his head!\"' 'How dreadfully savage!' exclaimed Alice. 'And ever since that,' the Hatter went on in a mournful tone, 'he won't do a thing I ask! It's always six o'clock now.' A bright idea came into Alice's head. 'Is that the reason so many tea-things are put out here?' she asked. 'Yes, that's it,' said the Hatter with a sigh: 'it's always tea-time, and we've no time to wash the things between whiles.' 'Then you keep moving round, I suppose?' said Alice. 'Exactly so,' said the Hatter.",
        "status": "1",
        "created_at": "2021-12-26T04:51:49.000000Z",
        "updated_at": "2021-12-26T04:51:49.000000Z",
        "date": "Dec 26, 2021",
        "author": "Odie Schultz",
        "image_url": "http://127.0.0.1:8000/uploads/posts/4557289711a9eb887a3ad60bc53ce110.png",
        "user": {
            "id": 4,
            "first_name": "Odie",
            "last_name": "Schultz",
            "gender": null,
            "phone": "9201799834",
            "email": "steuber.era@example.net",
            "email_verified_at": "2021-12-26T04:51:40.000000Z",
            "status": "1",
            "image": null,
            "image_url": "http://127.0.0.1:8000/uploads/noavatar.jpg"
        }
    },
    
];